import { addArticle } from "./n9-add";

async function main() {
  await addArticle({
    title: "La plaza de La Romanilla",
    slug: "la-plaza-de-la-romanilla",
    byline: "Eduardo Quesada Dorador",
    pages: "7",
    excerpt:
      "O la necesidad de reavivar el debate cívico sobre temas urbanos en una situación democrática relativamente consolidada.",
    paragraphs: [
      `<em>O la necesidad de reavivar el debate cívico sobre temas urbanos en una situación democrática relativamente consolidada.</em>`,
      `La actuación urbanística de las dos últimas corporaciones municipales granadinas se ha visto lastrada por un desfase entre la indudable voluntad de intervenir en la ciudad para mejorar su fisonomía y su funcionamiento, por un lado, y la calidad del diseño con que se han abordado tales intervenciones, por otro, cuestión ésta cuyo balance se muestra mucho menos halagüeño que el que pueda extraerse de la primera. El recién conformado ámbito de la plaza de la Romanilla ilustra perfectamente, para bien y para mal, esta desconexión entre dos factores cuya necesaria coordinación constituye, en el caso de esta ciudad, un objetivo todavía hipotético.`,
      `La Romanilla es una plaza de nueva creación. En diciembre de 1981, ocupando la concejalía de urbanismo del Ayuntamiento de Granada José Miguel Castillo Higueras, se solicitó a una serie de arquitectos la presentación de ideas para la urbanización de lo que no era entonces más que un impresentable e improvisado aparcamiento sobre una cochambrosa extensión de cascajo apisonado. La negatividad de esta imagen, visible en el mismo corazón urbano de Granada, se veía multiplicada por la proximidad del solar al complejo monumental catedralicio cuya relevancia artística e histórica sobrepasa con mucho los límites de lo meramente local. Del conjunto de propuestas presentadas —que fueron exhibidas en parte en la exposición del <em>Avance del Plan General de Ordenación Urbana de Granada</em> en febrero de 1983— se seleccionaron dos, cuya fusión y desarrollo ulterior habrían de dar lugar al proyecto definitivo. El encargo en este sentido se acordó en la sesión de la comisión municipal permanente del 8 de noviembre de 1983 y el proyecto final fue concluido y firmado por sus autores, los arquitectos Francisco Alcón, Ricardo Bajo, Luis López Silgo y Santiago Oliveras, en abril de 1984. Las obras comenzaron poco después. El aspecto que ofrece en la actualidad el ambiente urbano resultante de éstas responde a lo planeado salvo ligeras modificaciones (bordillos de los alcorques en mármol blanco en lugar del granito gris previsto y bases de las farolas en mármol blanco de Macael en lugar del mármol rojo previsto en otros puntos de la operación). Algunos de los aspectos más aparentes de lo proyectado —protagonismo casi absoluto del pavimento y de las palmeras como único abrigo arbolado, prescindiendo, prácticamente por completo, de la jardinería y de elaboraciones arquitectónicas más complejas— enraízan con varios de los datos contenidos como fundamentales en el <em>Proyecto Palmería</em>. Este plan, original del arquitecto Alberto Campo Baeza, resultó ganador en 1978 del <em>Primer concurso Nacional Almería de Arquitectura y Urbanismo</em> que proponía, como tema obligado de la convocatoria, la remodelación de la plaza que sirve de atrio a la Catedral almeriense. La mezcla del juego de palabras implícito en el título esconde, no obstante, un proyecto caracterizado por una notable brillantez conceptual, que fue publicado por Luis López Silgo y Francisco Salazar en el número dos (junio-julio de 1978) de <em>Arquitectura/Andalucía Oriental</em>, revista del C.O.A.A.O.`,
      `Pero la Romanilla era un problema diferente: el espacio a remodelar —definido, antes que por otro rasgo, por su complicada irregularidad— retaba a sus remodeladores con una situación de partida bastante más dificultosa que la ofrecida por la plaza almeriense. Del reconocimiento de estas dificultades no cabe deducir, sin embargo, la imposibilidad de que el solar de la Romanilla admitiese una resolución urbanística y ornamental de alto nivel cualitativo, caso que no es, en mi opinión, el que plantean el proyecto y la realización actuales, un proyecto y una realización formalmente fallidos. El caos topográfico del solar inicial se ha visto parafraseado en un conjunto un tanto farragoso que persigue racionalizar la superficie distinguiendo dos niveles que no acaban de justificarse, al menos en la forma en que han sido establecidos. En efecto, la superficie superior —ocupada por un paseo longitudinal flanqueado por dobles hileras de palmeras— ha sido configurada aumentando su altura desde su parte central hasta el escalón abalaustrado que lo separa tajantemente del plano inferior, parte central y plano inferior que se unen, sin embargo, a pocos metros del escalón, convirtiendo a éste en un elemento carente de sentido. El tratamiento decorativo de este elemento, valorado como clave en la operación, no parece más afortunado: el chapado en mármol blanco de su tabica desmiente la impresión compacta que transmiten como imagen el adoquinado y los bloques de mármol que cercan los alcorques; la fea balaustrada que lo corona (que responde a la misma intencionalidad estilística <em>neoart-decó</em> que informa el resto del programa) resulta, por otra parte, superflua, y la pretendida rima entre el desabrido diseño de los balaustres, con dobles molduras escalonadas, y el de otros detalles de la obra que presentan análogos motivos, no queda entablada ni fácil ni eficazmente.`,
      `La segunda superficie de la Romanilla se sitúa en un nivel más bajo y limita con los alzados de la calle Capuchinas que, en este sector de su trayecto, ve desdibujado su trazado en una desacertada confusión entre calle y plaza que no logran contrarrestar los espacios ajardinados acotados a tal fin. En esta zona inferior se ha reservado una amplia superficie desnuda —tal vez excesivamente vacía— con objeto de no obstaculizar la potente visión de la torre de la Catedral volcada sobre la plaza. Subrayando este propósito, se han colocado en los puntos correspondientes palmeras de un tipo de bastante menor envergadura que las empleadas en el resto de la Romanilla. Estas palmeras más pequeñas y los jardines constituyen componentes muy minoritarios del aderezo vegetal de la plaza, al que aportan, por tanto, más incoherencia que variedad. La fuente circular —caracterizada por una inoportuna ambigüedad tipológica entre fuente y piscina— conforma, junto a la plataforma hexagonal a que aparece ligada, un conjunto fuera de lugar, sumamente deficiente como objeto decorativo para espacios públicos y completamente pasivo en su relación con los restantes pormenores del proyecto, tanto por su ubicación, en un extremo de la plaza, como por su chata morfología. En este aspecto, resulta algo más atinado —pese a su inadecuada combinación, en algunas zonas, con losas de mármol blanco— el pavimento de adoquines de granito gris formando figuras geométricas según tramas fijadas por líneas negras de adoquines de basalto. En especial el piso definido por paños de adoquín a la florentina dialoga satisfactoriamente con los interesantes diseños clasicistas de algunas de las fachadas del recinto. En cuanto a las farolas, parecen demandar, por sus materiales —el latón dorado en particular— y por el resabio <em>art-decó</em> de sus formas, una escala distinta, más propia de piezas de interior.`,
      `Las palmeras fueron, desde el momento mismo de su plantación, una de las facetas más polémicas del plan de creación del nuevo ambiente. Puede afirmarse con certeza que, en Granada, la palmera carece de tradición como arbolado público y que su único abolengo urbano ha radicado en ser un elemento a utilizar, aisladamente, componiéndolo con otros muchos, desde frutales o cipreses, en cármenes y jardines privados. Se trata, sin embargo, de un árbol indudablemente bello en sí mismo, cuyo funcionamiento estético o antiestético depende, sobre todo, del soporte arquitectónico en que se engaste. El fracaso ornamental de las palmeras de la Romanilla es atribuible, fundamentalmente, a los déficits cualitativos del diseño de la plaza, sin que esto niegue, en absoluto, la presumible mayor pertinencia de otro tipo de arbolado.`,
      `Considerado globalmente, el establecimiento de la última plaza granadina se revela como una operación de diseño mal resuelta, circunstancia que no logra atenuar el hecho de que la mayor parte de las intervenciones urbanas llevadas a efecto en los últimos años sean probablemente más erradas que la presente, desde el pasaje Diego de Siloé —burdo remedo de las realizaciones de Gallego Burín— a la <em>naïf</em> glorieta de Arabial. Son, en cualquier caso, intervenciones que, por su carácter fallido, no deben estimarse irreversibles.`,
    ],
  });
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
