import { addArticle } from "./n9-add";
import { db } from "../src/lib/db";

async function main() {
  await addArticle({
    title: "Un manifiesto romántico: el prólogo a «Cromwell»",
    slug: "un-manifiesto-romantico-el-prologo-a-cromwell",
    byline: "Juan A. Calatrava",
    pages: "19",
    excerpt:
      "El Prólogo de Víctor Hugo a «Cromwell» (1827) como condensada exposición de los grandes temas del Romanticismo: lo sublime y lo grotesco, el Genio y el Drama.",
    paragraphs: [
      `La celebración del Centenario de la muerte de Víctor Hugo, que se anuncia en Francia con toda la <em>grandeur</em> que allí otorgan a los miembros de su Panteón, puede servir, pomposidades aparte, para algo positivo: replantearse una vez más, y seguramente no la última, una reflexión colectiva sobre el fenómeno del Romanticismo, de tan confusa determinación todavía en algunos de sus aspectos y, sin embargo, de tan enorme importancia en la construcción del pensamiento burgués moderno.`,
      `Su gigantesca obra literaria es, por supuesto, uno de los más importantes conjuntos a analizar en una reflexión semejante. Pero, junto a ello, se olvida a menudo que Hugo reflexionó en ciertas ocasiones sobre su propia obra, que el Romanticismo es esencialmente crítico y que tales <em>escritos críticos</em> deben ocupar, en el análisis global de la producción del autor, un lugar nada desdeñable. En este sentido, expondré a continuación las líneas maestras de uno de ellos, quizás el más importante, o cuando menos el más conocido, el <em>Prólogo</em> que Hugo escribió en 1827 para su obra <em>Cromwell</em>. Dicho texto se ha considerado a menudo como el verdadero manifiesto del Romanticismo: consideración falsa si se tiene en cuenta el carácter multiforme y complejo del fenómeno romántico, muy variable según las formaciones sociales en que se inserta. Ello hace que exista una cierta cantidad de escritos que podrían también reivindicar este título de <em>manifiesto romántico</em>, como son los casos conocidos del Prólogo de Walter Scott al <em>Castillo de Otranto</em> de Walpole, <em>La Cristiandad o Europa</em> de Novalis, los fragmentos de los hermanos Schlegel, etc.`,
      `Lo que sí es cierto es que el texto de Víctor Hugo es uno de los posibles manifiestos románticos, en el sentido de que presenta una condensada exposición de los principales temas del Romanticismo, aunque con las peculiaridades que lo hacen distinto de otros manifiestos. Escrito en 1827, en un momento en que la discusión clasicismo/romanticismo era ya prácticamente tema resuelto en Inglaterra y en Alemania, debatido en Italia y, paradójicamente, casi todavía no planteado en España, las específicas condiciones políticas e ideológicas de la Restauración francesa, pese a haber entrado ya en su fase última, hacían lamentar a Víctor Hugo que existiera, aún dominante, un Antiguo Régimen literario similar al Antiguo Régimen en política, y transformaban dicho planteamiento la propuesta estética de Hugo hasta dotarla de un alcance y unas aspiraciones liberadoras en las que el Romanticismo se siente, ante todo, como una poderosa fuerza rompedora de clisés y viejos esquemas.`,
      `Se hace necesario, así, comprender que los llamados Romanticismos nacionales, que, pese a compartir una misma matriz, presentan entre sí sustanciales matizaciones, no deben su existencia particular a supuestas idiosincrasias, sino a algo mucho más real: la pura materialidad de las distintas formaciones sociales europeas en las que se insertaron. El Romanticismo no puede entender la teoría del Genio en Víctor Hugo sin tener en cuenta las intuiciones anteriores de Diderot sobre el mismo tema (pese a que éste no se atrevió a llevar al Sujeto burgués desde las formulaciones de los <em>philosophes</em> hasta el Genio sin límites de los románticos). Y aún más: no se puede, por ejemplo, entender la teoría del Genio en Víctor Hugo sin tener en cuenta las instituciones anteriores de Diderot sobre el mismo tema (pese a que éste no se atrevió a desarrollarlas hasta sus últimas consecuencias); ni el nuevo modelo de sensibilidad ante la Naturaleza puede desconocer el papel de puente que representa la figura de Rousseau. Víctor Hugo y otros como él se convertirán, así, en fieles cronistas del tortuoso pero reconstruible camino que conoce el Sujeto burgués desde las formulaciones de los <em>philosophes</em> hasta el Genio sin límites de los románticos. Y si hiciera falta una obra de Víctor Hugo para demostrarlo, ahí está <em>El Noventa y Tres</em>, donde todas las categorías de la crítica romántica se condensan apiñadamente sobre una nueva visión, en clave de lo Sublime, de los hechos revolucionarios de 1793.`,
      `El <em>Prólogo a Cromwell</em> encierra, del mismo modo, una reinterpretación global de la historia de la Cultura, y, en el fondo, de la historia de la Humanidad, en un tono que, excluyendo definitivamente cualquier compromiso con el racionalismo ilustrado, asume, sin embargo, su herencia del mismo modo que la Francia moderna renegó de la Revolución asumiéndola a través de Bonaparte. Para Hugo, la literatura ha conocido tres grandes épocas. En la llamada Época Primitiva, a la que describe con fuertes tintes rousseaunianos, es, por supuesto, la lírica la forma literaria dominante, aunque, paradójicamente, no se encuentra ningún sentimiento de nostalgia con respecto a ese sentimiento lírico primitivo, que se ve inexorablemente superado por la Historia en la siguiente etapa. La Época Antigua, en efecto, coincide con el origen y desarrollo de las formas de sociedad (en tanto que en la fase anterior, como dice Hugo, «había familias y no pueblos; padres y no reyes»), y a ella corresponde, como era de esperar, la épica.`,
      `La llamada Época Moderna registra en cambio un acontecimiento decisivo: la aparición del cristianismo. En las páginas en las que Hugo se refiere a este fenómeno, todas las grandes claves del romanticismo se ven reinterpretadas en clave cristiana: el desesperado sentimiento de escisión entre el alma y el cuerpo, lo espiritual y lo material, el hombre y la Naturaleza; el despertar del corazón por el nuevo soplo que le infunden las grandes revoluciones y las catástrofes terrenales (y aquí hay que recordar de nuevo a Diderot, cuando afirmaba que las épocas de grandes catástrofes son las más propicias para la aparición y desarrollo del Genio estético, o cuando, en contra de muchos de sus contemporáneos, valoraba al Cristianismo en cuanto que, al ser una religión cruel y sangrienta, podía suministrar temas capaces de producir emociones estéticas mucho más eficaces que los fríos dioses paganos); la victoria del Norte salvaje sobre el Sur civilizado, etc. El cristianismo es, para Víctor Hugo, condición primera y esencial para el surgimiento de esa nueva literatura a la que aspira. El cristianismo lleva al poeta a la comprensión básica que debe guiar el trabajo del genio: la idea de que todo es dual, y de que por tanto en la Naturaleza no hay sino mezcla. De ahí surgirá una nueva noción de lo Bello: «Hará lo mismo que la Naturaleza: mezclará en sus creaciones, pero sin confundirlos, lo grotesco con lo sublime, la sombra con la luz; en otros términos, el cuerpo y el alma, la bestia y el espíritu». El Genio moderno nace, justamente, de la unión de lo grotesco y lo sublime, y es multiforme y, como tal, opuesto a la simplicidad uniforme del genio de los antiguos. Es una unión de contrarios que el Artista debe saber dominar, so pena de convertirse en aprendiz de brujo (Hugo constatará, páginas más abajo, cómo junto al clasicismo existe ya un nuevo enemigo para los románticos: el falso romanticismo que ha surgido al amparo de lo verdadero), y que extrae su energía de la propia naturaleza. Lo Bello no es ya el Bello Ideal neoclásico: consiste precisamente en ese contacto contrapuesto con lo deforme que hace alcanzar a lo Sublime su grado más alto (y hasta qué punto Víctor Hugo llegó a poner en práctica esta tesis teórica puede comprobarse, por ejemplo, en <em>Han de Islandia</em>).`,
      `La plasmación de esta nueva teoría de la belleza es el Drama: un drama, ahora sí, esencialmente distinto al drama burgués propuesto por Diderot o Lessing. Un drama entendido casi como <em>obra de arte total</em>, que encierra a la epopeya y a la lírica desarrolladas, y que tiene, significativamente, como columnas fundadoras, a Dante, Milton y Shakespeare. Y, lo más esencial, el nacimiento de este drama moderno es, para Víctor Hugo, consecuencia del reconocimiento romántico de que el hombre es un ser doble y escindido: «Lo real resulta de la combinación perfectamente natural de dos tipos, lo sublime y lo grotesco, que se cruzan en el drama como se cruzan en la vida real y en la creación».`,
      `Ello le lleva, como corolario, a la necesidad de derrumbar las dos convenciones clásicas más importantes: la arbitraria distinción entre géneros y la regla de las tres unidades. El poeta dramático reclama para sí todo el poder que le otorga su íntima comunión con lo real, y llega a extender su dominio absoluto no sólo ya a los personajes sino también al propio escenario en el que se desenvuelven (al que define como una especie de personaje mudo indispensable). El Genio sin limitaciones es el nuevo amo del arte. El Arte no conoce ya mediocridades: se es o no se es, y no hay más reglas ni más modelos que aquellos que el Genio sabe aprehender de la propia Naturaleza. Este nuevo Genio es, a su vez, ya un Creador, y no un mero imitador de las bellezas de la naturaleza, porque Arte y Naturaleza son dos cosas esencialmente distintas: el drama moderno es un espejo de ésta, pero tocado por la varita mágica del Arte.`,
      `El estilo y la forma de ese nuevo Drama llegan a parecer, así, cuestiones de orden secundario: «El rango de una obra debe ser fijado según su valor intrínseco, y no según su forma. En este tipo de cuestiones no hay más que una solución. No hay más que un peso que pueda inclinar la balanza del arte: es el genio». Como dice en un momento posterior, siempre es preferible hacer poéticas a partir de una poesía que poesías a partir de una poética.`,
      `Todo ello se articula, por último, con la llamada a la aparición de un nuevo tipo de crítica, acorde con el nuevo modelo de escritor que se postula: «El gusto es la razón del genio. He aquí lo que pronto establecerá otra crítica, una crítica fuerte, franca, sabia... Será ella la que, uniéndose a todo lo que hay de superior y valeroso en las letras, nos librará de dos azotes: el clasicismo caduco y el falso romanticismo que se atreve a asomar a los pies del verdadero». Dos enemigos de los que todavía el más peligroso era, sin duda, el primero: «La cola del siglo XVIII se arrastra aún en el XIX; pero no seremos nosotros, los jóvenes que hemos visto a Bonaparte, los que llevemos esa cola».`,
      `Víctor Hugo escribía estas palabras en 1827. Sólo tres años más tarde, la Revolución liberal haría posible la primera representación de una obra suya, <em>Hernani</em>.`,
    ],
  });

  await db.article.update({
    where: { slug: "un-manifiesto-romantico-el-prologo-a-cromwell" },
    data: { section: "La fábrica de sueños" },
  });
}

main()
  .then(() => db.$disconnect())
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
