import { addArticle } from "./n9-add";

async function main() {
  await addArticle({
    title: "Víctor Hugo y la arquitectura",
    slug: "victor-hugo-y-la-arquitectura",
    byline: "Ángel Isac",
    pages: "17-18",
    excerpt:
      "Notre-Dame de París y el movimiento arqueológico francés: la arquitectura como «libro de piedra» y la utopía romántica del pasado.",
    paragraphs: [
      `Una novela, <em>Notre-Dame de París</em>, escrita en 1831, habría de ser un texto decisivo para el prestigio del movimiento arqueológico francés. Víctor Hugo hizo en ella una formulación literaria de las visiones del mundo medieval que compartían románticos y arqueólogos, Mme. Stäel y Arcisse de Caumont, Chateaubriand y Adolphe Didron, Prosper Mérimée y Ludovic Vitet, entre otros. No es extraño; con frecuencia, literatura y arquitectura han mantenido una cierta complicidad e intercambio, como ocurrió entre las novelas <em>góticas</em> y el revivir arquitectónico de la Edad Media. Las primeras sirvieron para imaginar escenarios perfectos en los que se situaban acciones y objetos que iban de lo heroico a lo sublime, de lo pintoresco a lo cómico, o del terror al divertimento. Su lectura —muy extendida a partir del último tercio del siglo XVIII— terminaba creando una sutil necesidad de construir, poseer, la misma arquitectura descrita por Horace Walpole, Ann Radcliffe, Charlotte Smith o Walter Scott. A la inversa, según Ruskin, era la superioridad de la arquitectura gótica (racionalidad y sentimiento) la que aportaba el elemento más atractivo en aquellas narraciones.`,
      `El texto de Víctor Hugo, no obstante, no es una <em>novela gótica</em>, en el sentido que la expresión tiene, fundamentalmente, en la literatura anglosajona. Y esto, por la misma razón que los arqueólogos románticos franceses no pensaron igual que sus colegas ingleses, ni las teorías restauracionistas de Viollet-le-Duc coincidían con las de Ruskin. De ahí, precisamente, la trascendencia que tuvo la publicación de <em>Notre-Dame de París</em>. En ella, el vate del romanticismo no diluye la narración en un tiempo fijo de la Historia, capaz de conmover y excitar sentimientos como ningún otro, pero que inevitablemente se pierde. La novela de Hugo no es sólo un medio de emoción sensible. Por el contrario, sus páginas denunciaron —si bien es cierto que con una fuerte carga de aquélla— el abandono de los monumentos medievales, y se convirtieron, así, en uno de los más influyentes apoyos del movimiento arqueológico, conservador y restaurador, que fue una de las realidades más notables de la cultura francesa de la primera mitad del diecinueve, por la diversidad de intereses, políticos y culturales, que en él confluyeron desde la creación de la <em>Comission des Monuments</em>, en plena Revolución.`,
      `Víctor Hugo, que se definía como «poeta por inspiración y arqueólogo por simpatía» (en <em>Notre-Dame</em> escribió que «... entonces todo el que nacía poeta era arquitecto»), que quiso ser Chateaubriand o no ser nada, y que hizo ruinas poéticas del Arco de Triunfo proyectado por Chalgrin a la gloria de Napoleón, enfrentó la poesía a los <em>démolisseurs</em> cuando escribió la oda <em>La Bande Noire</em>, en 1823. Su pasión arqueológica era algo más que un argumento literario. Por este motivo, permaneció mucho tiempo ligado al grupo de intelectuales y arquitectos-arqueólogos que dieron forma al modélico aparato institucional destinado a proteger las ruinas monumentales, pero también cualquier otra riqueza cultural heredada del pasado. En 1836, Guizot creaba un «Comité des monuments inédits de la littérature, de la philosophie, des sciences et des arts considérés dans leurs rapports avec l'histoire générale de la France», del que formaban parte, junto a Victor Hugo, Cousin, Vitet, Le Prévost, Mérimée, Lenormant, Lenoir y Didron.`,
      `Para esta fecha, Víctor Hugo ya había declarado la <em>Guerre aux démolisseurs</em>, a través de la importante <em>Revue des Deux Mondes</em>, poco después de la publicación de <em>Notre-Dame de París</em>. Aquella declaración suscitó una intensa polémica, que finalmente resumiría Didron en <em>Vandalisme et mouvement archéologique</em> (1846). Antes, Montalembert, en la citada revista, había dirigido a Victor Hugo una carta en la que escribía: «Monsieur, votre mémoire sera toujours bénie par ceux qui ont voué un culte à l'histoire et aux souvenirs de la patrie; et la postérité inscrite parmi vos plus belles gloires celle d'avoir premier deployé un drapeau qui pût rallier toutes les âmes jalouses de sauver les monuments de l'ancienne France». Tal reconocimiento fue compartido también por Didron, el influyente director de <em>Annales Archéologiques</em>, quien escribió que le debía a Hugo su dedicación a la arqueología.`,
      `<em>Notre-Dame de París</em>, en general, todos los textos de Victor Hugo sobre temas de arquitectura, pueden explicarse por la sugestión que ejercían los objetos arquitectónicos entre los escritores románticos. Goethe, elogiando la catedral de Strasburgo, o Friedrich Schlegel, abogando por la culminación de la catedral de Colonia, habían establecido una peculiar literatura arquitectónica. Víctor Hugo también contribuyó, con el éxito de la novela, a que se iniciaran los trabajos de restauración de Notre-Dame, aunque nunca compartió el proyecto presentado por Viollet-le-Duc y Lassus, en 1843. En la novela, Víctor Hugo ya había advertido que, entre los daños que sufría la arquitectura gótica, también se encontraban algunas <em>restauraciones</em>.`,
      `En la mente del novelista, la catedral era un <em>edificio sublime y majestuoso</em> alzado sobre una ciudad armónica; por eso, desprecia la jactancia de Voltaire cuando éste ignoró la existencia de la catedral, al enumerar las obras más bellas anteriores a Luis XIV. La ciudad gótica fue, para Víctor Hugo, <em>una hermosa ciudad, una ciudad homogénea, una crónica de piedra</em>, en la que, como poco después intentaría demostrar Pugin, los edificios se integraban sin producir disonancias. En la ciudad moderna, por el contrario, la mirada de Hugo encuentra algunas cúpulas que parecen una <em>tarta de Saboya</em>, otro edificio es <em>producto de pastelería</em> o se confunde con <em>una gorra de jockey inglés</em>. La imaginación, en sentido retroactivo, le conduce a sugerir: «Rehaced el París del siglo XV, reconstruidlo en vuestra mente... Y luego, comparad». Es el principio de una utopía del pasado que tuvo muchos adictos a lo largo del siglo XIX.`,
      `Cuando Víctor Hugo diagnostica <em>esto matará a aquello</em>, lo hace bajo una doble afectación. En primer lugar, porque estaba convencido de que la arquitectura era un <em>libro de piedra</em> en el que toda la vida social quedaba reflejada: «La arquitectura —afirma— ha sido la gran escritura del género humano». En segundo lugar, porque suponía que la arquitectura, tras la descalificación de la Edad Media, había sufrido una <em>incontenible decadencia</em>. Con esta doble coartada, la culpabilidad que hacía recaer sobre la imprenta parecía no ofrecer dudas. La Historia impresa mataba al <em>libro de piedra</em>: la arquitectura, <em>poesía petrificada</em>. Desde ese instante, el arte arquitectónico «... ya no es el arte total, el arte soberano, el arte tirano»; en el curso de su decadencia, la arquitectura «... se despoja, se deshoja, adelgaza, es mezquina, pobre, nula». Con ella muere todo arte; <em>agoniza miserablemente</em>, según Víctor Hugo. «Que nadie se equivoque —insistía—, la arquitectura ha muerto, está muerta definitivamente, matada por el libro impreso». El genio poético, para Stendhal, moría en la misma fecha. Hegel —como siempre— viene a la memoria; pero, en su caso, el mismo diagnóstico no era más que la inconfesable limitación del Sistema, en el que ya no sería fácil acomodar ningún tipo de resurrección del arte, como predicaban los Nazarenos.`,
      `Durante todo el siglo XIX serán continuas las reflexiones sobre la decadencia de la arquitectura —y de las bellas artes, en general—, implicadas en revivir estilos del pasado o en justificar compromisos eclécticos. Todo esto ya no sería, para Hegel, más que espectros de una idealidad muerta. La dialéctica —aquello que salvó Marx— había sido para el Sistema lo mismo que la imprenta para la admirada arquitectura gótica de Víctor Hugo: la liquidación de un acuerdo perfecto entre Idea y Forma, Sociedad y Arquitectura. En un diálogo inventado por Paul Valéry, Fedro se dirige a Sócrates con palabras que bien pudieran definir la actitud de Víctor Hugo: «¡Pareces tú también vencido por la adoración de la Arquitectura! Ya no puedes hablar sin que el arte mayor te preste sus imágenes y su ideal estable».`,
    ],
  });
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
