/**
 * "Jardín deshecho: Los «Sonetos» de García Lorca" — Mario Hernández, con
 * introducción de Olvidos (nº9, págs. 20-24). Ensayo largo: HTML a mano
 * (intro editorial, epígrafe, el soneto, citas en verso y en prosa).
 */
import { db } from "../src/lib/db";
import { slugifyName } from "../src/lib/colaboradores";

const TITLE = "Jardín deshecho: los «Sonetos» de García Lorca";
const SLUG = "jardin-deshecho-los-sonetos-de-garcia-lorca";
const BYLINE = "Mario Hernández";
const PAGES = "20-24";
const EXCERPT =
  "A propósito de la edición pirata de los Sonetos del amor oscuro (1983): reconstrucción de la historia y los títulos del libro de sonetos de Lorca, del «amor oscuro» al «Jardín de los sonetos».";

// cita en prosa (más pequeña, sangrada)
const q = (t: string) => `<blockquote class="cita-prosa">${t}</blockquote>`;

const content = [
  // Introducción de Olvidos (preámbulo editorial)
  `<blockquote><p>Una inesperada y jugosa edición de los <em>Sonetos del amor oscuro</em> fue distribuida clandestinamente en 1983, desencadenando la publicación final, por parte de la familia, de algunos de los poemas inéditos más legendarios de Federico García Lorca. La oscuridad y el mito, suficientemente motivados por muchas cuestiones, eran ya inevitables cuando las páginas del periódico <em>ABC</em> dieron a la luz —con legalidad, pero a destiempo y en lugar extraño— los sonetos lorquianos. Para poner algo de orden en la nebulosa del secreto y el sentimiento, <em>Olvidos de Granada</em> ha creído oportuno ofrecer una reconstrucción objetiva de la historia de estos poemas: ¿cuál fue su verdadero devenir y la sucesiva intención de su autor? Por ello, hemos pedido permiso al conocido crítico lorquiano Mario Hernández para reproducir un artículo que, con este motivo, escribió destinado a la revista <em>El Crotalón</em>. Debido a su extensión, y para no manipular el contenido, damos aquí, sin las amplias notas que lo acompañan originalmente, solamente la primera parte, que, desde luego, guarda sentido por sí sola.</p></blockquote>`,

  `<p style="text-align:center;text-indent:0"><em>La Muerte y el Amor siendo perdidos<br>juntos pasaron una noche oscura...</em><br>— Alciato</p>`,

  `<p>Mediado ya el mes de diciembre de 1983, pero con matasellos de Granada en el rojo sobre, del día 14, recibo sin remite (y agradezco) una edición de los <em>Sonetos del amor oscuro</em>. La edición, aparte de pirata, es de una anonimia absoluta: carece de nombre de autor, así como se omiten los del impresor y editor, probablemente coincidentes hasta en el trabajo manual de la impresión. Para rizar el rizo, tampoco se consignan los nombres de Aleixandre y Neruda como autores de dos fragmentos de prosas, alusivos a los sonetos, que anteceden a la edición. Unos puntos suspensivos sustituyen incluso, en el texto aleixandrino, el nombre de Federico. El editor ha añadido, de minerva propia o amiga, un tercer texto en prosa didáctico-lírica: cuatro breves párrafos más una frase última como piedra de identificación para ciegos. Los oscuros sonetos, se dice, constituyen ¡Sombra inmemorial del poeta de la alegría! El colofón explicita con sangrantes versales: «ESTA PRIMERA EDICIÓN DE LOS / SONETOS DEL AMOR OSCURO / SE PUBLICA PARA RECORDAR / LA PASIÓN / DE QUIEN LOS ESCRIBIÓ. / GRANADA, EN EL OTOÑO DE / 1983». En la memoria remota de quien escribió estas líneas impresas en tinta roja, quizá resonará un título de Luis Rosales: <em>Pasión y muerte del conde de Villamediana</em>. Por otro lado, el otoño granadino ha sido elegido como pretexto simbólico, pues casi con toda seguridad la edición se ha realizado a muchos kilómetros de la ciudad andaluza. Todo induce a pensar que el intencionado rescate se ha unido a un juego literario propio de entendidos en la salida a escena de esta edición no venal, cuya tirada es de 250 ejemplares numerados, según los datos de la página de créditos.</p>`,

  `<p>Tanto misterio está servido con pulcra exquisitez. Los sonetos se reproducen en un cuadernillo en octavo de 24 páginas, contando las de respeto. Tapas y hojas están sujetas, en el mínimo lomo, por un cordón rojo trenzado. La cubierta, en cartulina de un rojo acarminado, sólo ofrece el título, impreso en caracteres Bodoni, los mismos que se usan, en cuerpos distintos, para las notas preliminares, sonetos y colofón. La impresión se ha hecho sobre un papel verjurado Ingres de la casa Guarro, de color rosado, en perfecto acorde con la tinta roja utilizada, que sólo cambia a negra en cubierta y adorno de la contracubierta.</p>`,

  `<p>La portada repite el título de la serie y añade los años supuestos de composición: 1935-36. Con toda probabilidad, los once sonetos que este cuaderno recoge fueron escritos (o comenzados como serie) en 1935, parte de ellos en el mes de noviembre y en Valencia. En cuanto al título elegido, <em>Sonetos del amor oscuro</em>, no puede ser aceptado sin reticencias. No cabe duda alguna de que fue uno de los títulos, quizás el primero, pensado por Lorca para su libro en preparación. Debemos su conocimiento a uno de sus mejores amigos, Vicente Aleixandre, quien lo recoge en una célebre evocación de 1937: «Federico». Aparecerá repetido después en páginas de amigos diversos, de Cernuda (1938) a Neruda (1968). En estos dos casos, máxime en el segundo, el recuerdo del título se apoya probablemente en el texto aleixandrino. Cernuda, no obstante, añade precisiones de importancia sobre el contenido del libro en 1954, siempre a partir de sus recuerdos personales.</p>`,

  `<p>Junto a estos testimonios, cabe traer a colación un texto del propio Lorca. Al fin de su conferencia <em>La imagen poética de don Luis de Góngora</em> (1925-1926) añadió en la revisión del texto hecha en 1930: «El marqués de Sieteiglesias muere en la horca para que su orgullo viva, y el delicado gongorino marqués de Villamediana cae atravesado por las espadas de sus amores oscuros». Como explica el editor de esta conferencia, el poeta se hacía eco de la tesis contenida por Narciso Alonso Cortés, que en <em>La muerte del conde de Villamediana</em> (Valladolid, 1928) relacionó el asesinato del poeta barroco con su bisexualidad. La cita esclarece el significado, comúnmente admitido, del título lorquiano, además de justificar con un antecedente la verosimilitud de su elección. No obstante, las connotaciones del sintagma <em>amor oscuro</em> se disparan en más de una dirección. Implícita queda en algún verso la alusión a la noche oscura del alma, la vía purgativa de los místicos. La complejidad de la visión aparece en un soneto del que sólo se conserva un borrador. Añado puntuación por necesidad ineludible:</p>`,

  `<blockquote>Ay voz secreta del amor oscuro,<br>¡ay balido sin lanas! ¡ay herida!<br>¡ay aguja de hiel, camelia hundida!<br>¡ay corriente sin mar, ciudad sin muro!<br><br>¡Ay noche inmensa de perfil seguro,<br>montaña celestial de angustia erguida!<br>Ay perro en corazón, voz perseguida,<br>silencio sin confín, lirio maduro.<br><br>Huye de mi caliente voz de hielo,<br>no me quieras perder en la maleza<br>donde sin fruto gimen carne y cielo.<br><br>Deja el duro marfil de mi cabeza,<br>¡apiádate de mí! ¡rompe mi duelo!<br>¡que soy amor, que soy naturaleza!</blockquote>`,

  `<p>El soneto, con sus evidentes malos versos, como el 12, tiene algo de poema en agraz, asentado en un énfasis emotivo que lo llena hasta el límite de signos de admiración, por encima, incluso, del hábito exclamativo del poeta. Como en el <em>Poema doble del lago Eden</em>, de <em>Poeta en Nueva York</em>, también aquí dos voces aparecen opuestas: la del yo poético, controlado en su apasionamiento —<em>caliente voz de hielo</em>—, frente a la angustiosa y nocturna del amor oscuro. Y esta voz secreta, si por un lado perseguida (se supone que socialmente), también hiere y amenaza o persigue ella misma —<em>perro en corazón</em>—, hasta aparecer asociada a la muerte: <em>silencio sin confín, lirio maduro</em>. De ahí que el poeta se defienda frente al poder obsesivo de la segunda voz y contraponga en el último endecasílabo su identificación del yo íntimo con otro amor, el regido por la naturaleza. Frente a él se erige la maleza sin fruto, la frustración de la esterilidad en que amorosamente gimen carne y cielo.</p>`,

  `<p>El amor cantado es oscuro porque se ofrece indefectiblemente asociado a la muerte. Si Lorca es uno de los grandes poetas amorosos de la literatura en lengua española, lo es desde una actitud en que lo elegíaco cobra poderosísimo relieve: elegía que no es llanto por lo que se pierde, sino radical frustración ante lo concebido como inalcanzable, ilimitado. Así, el amor llega a alcanzar tintes metafísicos: «¡Amor de siempre, amor, amor de nunca!» (<em>Tu infancia en Menton</em>), y el poeta necesitará acudir, muchas veces de manera soterrada, a un simbolismo religioso de raíz católica. Baste un ejemplo, de la <em>Casida de los ramos</em>:</p>`,

  `<blockquote>El Tamarit tiene un manzano<br>con una manzana de sollozos,</blockquote>`,

  `<p>donde el árbol del Paraíso, o tenido por tal, presenta una sola manzana de amargura, como en el mito bíblico.</p>`,

  `<p>La naturaleza, de algún modo aprendida en Rubén Darío, implica en Lorca fecundación, perpetuación de la vida. «Porque el agua da sal, la tierra fruta», canta Yerma ante la angustiosa excepción de su esterilidad <em>contra natura</em>. La fecundidad de lo vivo supone una vía para anular el antagonismo entre amor y muerte, aunque al poeta no se le escape otra posibilidad trágica, expresada con lenguaje modernista ya en el prólogo a <em>El maleficio de la mariposa</em>: «¡Cuántas veces el enorme esqueleto portador de la guadaña, que vemos pintado en los devocionarios, toma la forma de una mujer para engañarnos y abrirnos las puertas de su sombra! Parece que el niño Cupido duerme muchas veces en las cuencas vacías de su calavera». Es en este contexto global donde debe entenderse el soneto arriba transcrito: el poeta se debate contra la irrupción, marcada por las insistentes anáforas, de una voz que implica muerte y esterilidad, conceptos que se ofrecen como sinónimos. Ha escrito José Ángel Valente:</p>`,

  q(`Lorca sintió con particular acuidad esa muerte segunda o forma primitiva de la muerte que sería la imposibilidad de engendrar. El tema se manifiesta con insistencia, a veces desde actitudes contradictorias. (...) Parece, por supuesto, indispensable remitirse para todo posible análisis del tema a la naturaleza no germinativa de la relación homosexual. Pero quizás importe señalar que la homosexualidad, aunque condiciona a todas luces el problema, no lo determina necesariamente. (...) Se siente la necesidad de engendrar o reengendrarse, la necesidad de no morir. Sólo en función de esa necesidad la relación homosexual opera como condicionante contradictorio o patético.`),

  `<p>De ahí también la excepcionalidad en la obra lorquiana de alguno de estos sonetos de amor, no sólo por su directa y emotiva confesionalidad amorosa, sino por ser, en palabras extremadas de Aleixandre, «prodigio de pasión, de entusiasmo, de felicidad, de tormento, puro y ardiente monumento al amor». Frente a <em>Poeta en Nueva York</em>, frente al mismo <em>Diván del Tamarit</em>, el tono ha variado de manera perceptible. Y ante la pluralidad de voces que Lorca distingue en su propia poesía, ahora rescata, más que nunca, aquélla que describía en una carta a Jorge Guillén: «Amo la voz humana. La sola voz humana, empobrecida por el amor y desligada de paisajes <em>que matan</em>. (...) La poesía es otro mundo. Hay que cerrar las puertas por donde se escapa a los oídos bajos y a las lenguas desatadas. Hay que encerrarse con ella. Y allí dejar correr la voz divina y pobre, mientras cegamos el surtidor. El surtidor, no». Es la búsqueda, tan insistente, de la autenticidad del sentimiento —en teatro y poesía—, por encima de las modas literarias, a cuyo poso histórico es obvio que no pudo ser ajeno. En la lucha entre realidad y fantasía Lorca prefiere la primera o levanta su mundo literario a partir de la pugna entre ambas. De ahí que en el citado <em>Poema doble</em> manifieste la búsqueda, frente a un yo literariamente ficticio, de su nombre auténtico:</p>`,

  `<blockquote>para decir mi verdad de hombre de sangre,<br>matando en mí la burla y la sugestión del vocablo.</blockquote>`,

  `<p>«¡Qué raro que me llame Federico!», había dicho en <em>Canciones</em>. Laberinto de espejos, de identidades interrogantes, de voces en pugna. Uno de los sonetos de amor se titulará <em>El poeta dice la verdad</em>, lo que no significa, como podría creerse ingenuamente, que el poeta dice, al fin, su verdad. Como tantos poetas a través de los siglos, Lorca canta y dice la verdad de su amor. Verdad y mentira son nuevas formas que adopta el conflicto entre realidad y fantasía, hondamente dramatizado en su teatro. La opción de Lorca es clara, aun por vías de sutil complejidad.</p>`,

  `<p>Vicente Aleixandre ha manifestado que el título <em>Sonetos del amor oscuro</em> tenía carácter provisional. No se conoce, por otra parte, ningún manuscrito poético, carta o declaración a la prensa en donde el título quedara consignado. Lorca sólo habló del libro en dos entrevistas. En la primera, que en contra del periodista que la hizo retrotraigo a enero de 1936, declaraba: «Mientras se estrenaba <em>Doña Rosita la soltera o el lenguaje de las flores</em>, yo estaba tranquilamente en mi cuarto del hotel terminando unos sonetos». Dicho estreno, al que sí asistió el autor, tuvo lugar en Barcelona el 12 de diciembre de 1935. Dos días después, el poeta leía su <em>Epitafio a Isaac Albéniz</em> ante la tumba del músico. El borrador de este soneto se conserva sobre papel que ostenta el membrete del Majestic Hotel Inglaterra, donde Lorca se alojaba en Barcelona. Del cotejo con el primero de la declaración se deduce con claridad que el <em>Epitafio</em> debía pertenecer intencionalmente al intitulado libro. La hipótesis no contradice la posibilidad de que Lorca escribiera más sonetos en las fechas a que se refiere, aunque no hay ninguna prueba en este sentido. A la vista de la documentación conocida, el término <em>libro</em> no pasa de ser una típica hipérbole lorquiana. En cuanto a la expresión «estaba (...) terminando», podría estar referida, además de al soneto indicado, a una simple revisión de los ya escritos.</p>`,

  `<p>La segunda entrevista es ya de abril del 36. El poeta sostenía entonces: «Tengo cuatro libros escritos que van a ser publicados: <em>Nueva York</em>, <em>Sonetos</em>, la comedia sin título y otro. El libro de sonetos significa la vuelta a las formas de la preceptiva después del amplio y soleado paseo por la libertad de metro y rima. En España el grupo de poetas jóvenes emprende hoy esta cruzada». El escueto título enunciado —<em>Sonetos</em>— es el único del que queda constancia por declaración expresa de Lorca, aparte de ser aparentemente posterior al recordado por Aleixandre. El que el poeta se decantara por un título puramente definitorio de la forma estrófica sugiere, además, que el contenido del libro había dejado de ser unitario. Por otra parte, la aparición en enero del 36 de <em>El rayo que no cesa</em>, de Miguel Hernández, es un síntoma de la vuelta al soneto que se estaba produciendo entre los poetas de la generación más joven, como notaba Lorca. Junto al libro hernandiano, han de citarse los sonetos que Luis Rosales incluye en <em>Abril</em> (Cruz y Raya, 1935) y los diecisiete <em>Sonetos amorosos</em> (Héroe, 1936) de Germán Bleiberg. Tácitamente subyacía una pugna entre una corriente clasicista —como si en las últimas habitaciones surrealistas se quemaran por pastillas Bécqueres y Garcilasos— y el neobarroquismo quevediano de un Hernández. Quevedo, no se olvide, ya es fuente de inspiración del albertiano <em>Sobre los ángeles</em> (1929), resuena en los sonetos de la elegía <em>Verte y no verte</em> (1935), es antologizado por Neruda para Cruz y Raya, aparte de dejar su huella en <em>Residencia en la tierra</em> (1935), y es tema anunciado de una conferencia que Lorca proyectaba dar en México.</p>`,

  `<p>Mención aparte merece otro juvenil libro de sonetos, <em>Misteriosa presencia</em> (Madrid: Héroe, 1936), primera obra poética de Juan Gil-Albert. Destaco esta colección de sonetos amorosos, dirigida a un tú masculino sin veladura alguna, porque Lorca tuvo conocimiento de ella en un momento significativo. Ha recordado Gil-Albert:</p>`,

  q(`En aquella su última visita a Valencia le leí algunos de los sonetos que aparecían en las Ediciones Héroe de Manolo Altolaguirre, a medio paso de la sublevación militar, con el título de <em>Misteriosa Presencia</em>.`),

  `<p>Dicha visita está datada en noviembre de 1935, en días en que Lorca escribe o inicia la composición —en papel de cartas del hotel Victoria— de sus propios sonetos amorosos. Aunque poco o nada les ligue a los duros poemas de Gil-Albert, cabe preguntarse si aquella lectura amistosa no fue el desencadenante circunstancial que provocó la serie lorquiana. Cuando menos, valga retener otro dato demostrable: Gil-Albert fue uno más de los poetas amigos que escuchó a Lorca sus sonetos, según analizaré después. Y esta lectura del granadino, gustoso de expandir oralmente su poesía, pudo tener lugar en Valencia —aunque no descarto que se produjera, o se repitiera, ya en Madrid—. Allí llegaría Gil-Albert a principios de 1936, «en aquellas vísperas atroces», y permanecería hasta después del asesinato de Calvo Sotelo (13 de julio). Puesto que comentó con Lorca este suceso, el poeta valenciano se contaría entre las personas que vieron a Lorca poco antes de su último viaje a Granada. En la mañana del 14 de julio Lorca ya se encontraba en la ciudad donde hallaría muy pronto la muerte.</p>`,

  `<p>En la segunda entrevista el poeta granadino da a entender que el libro de sonetos estaba escrito y presto para su edición, al igual que <em>Poeta en Nueva York</em> y el libro no especificado, seguramente <em>Diván del Tamarit</em>, cuya edición venía retrasándose. De la comedia sin título sabemos con certeza que no llegó a ser terminada, lo que ya hace dudar sobre el resto de la afirmación. En cuanto a los <em>Sonetos</em> conocemos dos testimonios absolutamente fiables y de fechas próximas que precisan, aun de modo contradictorio, las palabras del poeta. Fueron escritos por Pablo Suero y Gabriel Celaya, los dos en 1936 y a partir de lecturas oídas a Lorca.</p>`,

  `<p>Parece que el poeta granadino tenía por costumbre llevar consigo, en el bolsillo de la chaqueta, los manuscritos de lo que estaba escribiendo, como hacía Unamuno. Refiriéndose a una etapa que se sitúa en torno a 1918, lo afirma Mora Guarnido desde sus recuerdos de amistad juvenil. Que la costumbre pervivió nos lo muestra Adolfo Salazar, quien escribe en 1938 sobre la última pieza teatral terminada por el poeta: «Federico vivía en Madrid frente por frente de mi casa. Cada vez que terminaba una escena venía corriendo, inflamado de entusiasmo. (...) Federico leía la obra a todos sus amigos, dos, tres veces cada día. (...) Federico llevaba constantemente en su bolsillo el original de <em>La casa de Bernarda Alba</em>».</p>`,

  `<p>El dato se comprueba por el mismo estado en que se han conservado los manuscritos. Salvo casos excepcionales, Lorca escribía sus poemas y piezas de teatro en cuartillas de tamaño común. El manuscrito, plegado después por el centro, iba a parar al bolsillo en caso necesario, y allí sufría el deterioro correspondiente, máxime en un papel que no solía ser de calidad especial. En los autógrafos de teatro, cuyas hojas eran foliadas de modo independiente para cada acto, la última por acto y en especial la del tercero muestran huellas más evidentes de este uso. Otro es el caso de los poemas, que cuando no corresponden a una copia en limpio (del <em>Poema del cante jondo</em>, por ejemplo), se presentan en hojas independientes, raramente foliadas. Algunas, sobre todo las de <em>Poeta en Nueva York</em> guardadas en el archivo familiar, se han llegado casi a rasgar en algún caso por el doblez central, señal de los avatares que sufrieron en múltiples lecturas, viajes y conferencias. Un poema suelto, <em>Crucifixión</em>, en autógrafo que conservó inicialmente M. Benítez Inglott, ofrece hoy las mismas características: rasgado enteramente por el doblez y con los bordes sumamente desgastados. También los pliegos u hojas donde fueron escritos los sonetos aparecen con la marca de haber estado doblados por el centro y con el mismo inicio de rotura por la línea de ese doblez.</p>`,

  `<p>A juzgar por las lecturas de que se tiene noticia, el poeta debió llevar consigo los sonetos de la manera que se ha descrito. Ello explica que estas lecturas, dirigidas a un círculo privado, pudieran tener lugar en cualquier momento. Tiempo habría, una vez terminado el libro, de recitales públicos, incluso de redacción de un texto explicativo para las lecturas elevadas a conferencia: sobre el <em>Romancero</em>, sobre <em>Poeta</em>. En los meses de 1936 Lorca va leyendo los sonetos a sus amigos, aun antes de que el libro esté concluido. Es lo que ocurrirá con <em>La casa de Bernarda Alba</em>, de acuerdo con el testimonio transcrito. Lectura, por tanto, no implica ni exige obra terminada.</p>`,

  `<p>Podemos fechar con seguridad una de estas lecturas, en febrero de 1936. Fue la dedicada a Pablo Suero, autor teatral y periodista argentino con quien Lorca había trabado amistad durante su estancia en los países del Plata. Por sus relaciones literarias y por sus colaboraciones en <em>Noticias Gráficas</em>, diario de Buenos Aires, Suero constituía un lazo de unión importante con el mundo argentino. Sabemos que llegó a Madrid, tras detenerse unos días en Barcelona, el cinco de enero. Deshechos por mediación de Ugarte y Neruda unos equívocos enfadosos —chismes ultramarinos, según Neruda—, los dos amigos volvieron a reunirse. Lorca le llevó entonces ejemplares del <em>Llanto</em>, de <em>Seis poemas galegos</em>, de <em>Primeras canciones</em> y de <em>Bodas de sangre</em>. Las dos últimas ediciones se terminaron de imprimir el 28 y el 31 de enero, según los colofones respectivos. El encuentro sucedería a primeros de febrero; Suero mismo recuerda que unos quince días después de su llegada, equivocándose en muy poco. Reanudada la amistad, una noche el poeta le leyó, en una taberna madrileña, varias de sus obras: un acto de un drama social (fragmento hoy perdido, a juzgar por su descripción), los <em>Títeres de cachiporra</em> (seguramente el <em>Retablillo de don Cristóbal</em>), y dos libros de versos: <em>Diván del Tamarit</em> y <em>Sonetos</em>. A éste se refiere Suero como «un libro de <em>Sonetos</em> de amor, de admirable belleza y penetrante originalidad». Ni rastro, pues, de <em>La casa de Bernarda Alba</em>, fechada en su última hoja el 19 de junio. Pero la lectura queda enmarcada por datos anteriores. El periodista relata como hecho próximo a aquella sesión una comida en la casa familiar de Lorca, presentes los padres del poeta, además de Francisco García Lorca y José F. Montesinos. Este «acaba de hacerle publicar, casi por fuerza, <em>Bodas de sangre</em> a Federico, robándole el manuscrito». Por otra parte, añade el relato, «era en vísperas de las elecciones», cuya fecha fue el 16 de febrero, cuando triunfa el Frente Popular. La lectura mencionada tuvo lugar, por consiguiente, en la primera quincena de febrero de 1936.</p>`,

  `<p>Suero consignó sus recuerdos poco tiempo después del comienzo de la guerra civil española. Todavía aludirá a la muerte del poeta como hecho poco creíble. Fresco, pues, el recuerdo de aquella lectura, menciona el libro bajo el escueto título de <em>Sonetos</em>. La coincidencia con la referencia de Lorca en la citada entrevista de abril sirve para confirmar la fidelidad de su memoria, pero asegura también la exactitud con que fue tomada la declaración del poeta. Entre febrero y abril, por tanto, el libro se titulaba <em>Sonetos</em> y había quedado en el olvido el título que, en mi opinión, sería anterior: <em>Sonetos del amor oscuro</em>. El testimonio de Suero fue escrito con anterioridad al de Aleixandre. No obstante, Suero habla de <em>Sonetos de amor</em>. Puesto que la alusión se hace al paso, sin pormenorizar detalles (si el libro estaba o no acabado, cuántos poemas lo componían, etc.), cabe pensar que la lectura se redujo a sonetos amorosos, o que sólo había uno o dos de otro tema, tal como señalaría Cernuda.</p>`,

  `<p>Frente a las afirmaciones de Lorca y de Suero se demuestra que el libro no estaba terminado a través de las notas del diario de Gabriel Celaya, quien se vio en marzo con el poeta granadino en San Sebastián. El día 7 de dicho mes Lorca dio, en el Ateneo donostiarra, su conferencia-recital sobre el <em>Romancero gitano</em>. Transcribo a continuación las palabras que Celaya anotó en su diario al día siguiente:</p>`,

  q(`Lo que Federico me ha dicho de mi libro (<em>Marea de silencio</em>) me ha dejado sorprendido. Lo esperaba todo menos eso. ¡En qué cosas se fija un lector! No ve el libro en sí. Se fija sólo en lo que él pueda reflejar de sus preocupaciones del momento. Muy natural, es verdad, pero ¡qué desconcertante! Así, Federico me dice: «Lo que yo he señalado en tu libro a Neruda y a Alberti es la preocupación por la forma. Es muy importante. Atravesamos momentos difíciles. Ese abandonarse sin orden ni medida (creo que se refiere a la escuela que empieza a rodear a Neruda) es muy peligroso. Yo, ahora —sigue— estoy escribiendo un libro de sonetos. Es necesario volver a esto. Me agrada por eso en tu libro la preocupación que en cada poema se advierte de construcción. Lo que tú practicas no es un clasicismo a ultranza. La gente no advertirá por eso tu preocupación por la forma. No se dan cuenta de que el versículo que tú empleas no es una innovación, sino la más clásica de las fórmulas».`),

  `<p>Está claro que Lorca, remontándose quizás al versículo bíblico, buscaba y encontraba en <em>Marea de silencio</em> (Zarauz: Itxaropena, 1935) un clasicismo del que Celaya, que ya había escrito para entonces <em>La soledad cerrada</em> (publicado en el 47), se sentía completamente ajeno. Un clasicismo, entiéndase, semejante al cultivado por algunos de los poetas jóvenes del momento, como Rosales o Bleiberg. Tácitamente el poeta granadino se declaraba en contra de un surrealismo residual que había contaminado la creación incipiente de otro grupo de poetas jóvenes. Las pruebas están, entre otras publicaciones, en las páginas de <em>Caballo verde para la poesía</em> —título y dirección de Neruda—, cuyo primer número, de octubre del 35, se abría con un conocido manifiesto antijuanramoniano: «Sobre una poesía sin pureza». Inédito aún <em>Poeta en Nueva York</em>, agudamente corregido desde sus borradores primeros, es muy probable que Lorca aprobara en casi todos sus puntos el texto nerudiano, pero su foco de atención adoptaba una dirección distinta. Su no nueva insistencia incide en el problema de la <em>construcción</em> del poema; huella clara de un clasicismo que siempre defendió. Es sintomático que, cuando en abril del 36 juzga <em>La realidad y el deseo</em>, el libro de Cernuda entonces recién aparecido, enumere los temas cantados por el poeta sevillano y los subraye como «expresados en norma, en frialdad, en línea de luz, en arpa». La alusión becqueriana —último término de la enumeración— se engarza con sustantivos que aluden a una conciencia plena en la ejecución inteligente del poema. Ya en 1924, a propósito del soneto funeral dedicado al poeta ultraísta Ciria y Escalante, escribía en una carta: «porque el soneto guarda un eterno sentimiento que no cabe en otro frasco más que en éste aparentemente frío».</p>`,

  `<p>De acuerdo, pues, con el diario celayano, el libro de sonetos seguía en proceso de elaboración, lo que no impide que Lorca presentara a veces la serie de poemas ya escritos como una unidad conclusa. Esto es lo que debió suceder ante Suero y en la citada entrevista de abril. Coincidiendo con Celaya, sin embargo, Cernuda se referirá a una lectura de los <em>Sonetos del amor oscuro</em> (así citados, 1938), como libro que Lorca estaba escribiendo. Cernuda escuchó los sonetos, según su recuerdo, en mayo del 36.</p>`,

  `<p>Aún omitiendo otros datos que no arrojan nueva luz sobre lo examinado hasta ahora, es de importancia revisar un último hecho. Claude Couffon (1962) recogió de labios de Luisa Camacho, tía de Luis Rosales, dos noticias de sumo interés: Lorca trabajaba, mientras permaneció en la casa granadina de los Rosales, de donde sería sacado hacia la muerte, en <em>La casa de Bernarda Alba</em>, que entonces retoca, y en un libro que llevaría por título <em>El jardín de los sonetos</em>. Henos, pues, ya en Granada y ante el tercer título dado por el autor a su colección de sonetos.</p>`,

  `<p>Es perfectamente verosímil que en aquellos días de agosto de 1936 —entre el 9 y el 16, según Gibson— Lorca, que en ningún momento debió temer por su vida, decidiera continuar con sus costumbres de trabajo. Si el verano fue siempre para él época fecunda de creación, casa con su proceder el hecho de que, al trasladarse a casa de los Rosales, llevara consigo los manuscritos de las obras que entonces le ocupaban. Los varios testimonios de los Rosales coinciden en que el poeta se comportó aquellos días con confianza y con su modo habitual de ser, incluso con rasgos de humor respecto a los bombardeos y la confusión de noticias de las diferentes emisiones radiofónicas. Gozó también de soledad para leer y escribir, por poco que fuera. Luisa Camacho y Esperanza Rosales, pero sobre todo la primera, en cuyo piso se alojaba, fueron las que le trataron diariamente, ausentes los hermanos Rosales en sus diversos cometidos de guerra, como partícipes señalados del levantamiento granadino. Por estas circunstancias tiene sumo valor el testimonio de Luisa Camacho ante Couffon, confirmado en casi todos sus puntos por Esperanza y Luis Rosales en declaraciones más tardías.</p>`,

  `<p>Por su parte, Jean-Louis Schönberg, cuyo papel en las interpretaciones sobre los motivos del asesinato de Lorca no es preciso comentar, escribía a propósito del entonces (1966) reconstruible como «léger bouquet des <em>Sonnets d'amour obscur</em>»:</p>`,

  q(`Au dire des initiés qui les ont lus ou entendus, Vicente Aleixandre, Luis Rosales, ils devaient former un <em>Jardín de sonnets</em>, comptant selon l'auteur d'<em>Abril</em>, une trentaine, peut-être trente-cinq pièces dont les plus anciennes remontent à 1924, époque de l'amitié avec Dalí; mais la plupart n'étaient pas destinés apparemment à la publication, vu leur ésotérisme et leur encens à Corydon.`),

  `<p>A pesar de la confusión del texto, es claro que los datos nuevos que se recogen proceden exclusivamente de Rosales. No obstante, en 1981 el autor de <em>Un rostro en cada ola</em> me indicaba que el <em>Jardín de los sonetos</em> (no <em>El jardín...</em>, ni <em>Jardín de sonetos</em>, según precisaba a mi pregunta) incluiría el dedicado a Ciria, precisamente de 1924. La datación de este soneto se sabía con seguridad desde la publicación del epistolario del poeta a Fernández Almagro en 1968. La sombra dudosa de Dalí (añadida o no por Schönberg) quedaba eliminada, sustituida con perfecta coherencia. De acuerdo con esta interpretación, el libro no era de una temática amorosa unitaria, sino que recogía sonetos de una temática distinta, ejemplificada en el citado. De este modo Rosales me confirmaba expresamente, y al mismo tiempo ampliaba, los datos transmitidos por Eisenberg en 1975:</p>`,

  q(`Luis Rosales explicó a Stinglhamber (Schönberg) que había unos 35 sonetos, que el <em>Jardín de los sonetos</em> se dividía en dos partes, que los sonetos más antiguos remontaban a 1925 y que se conservan «muchas copias entre los amigos».`),

  `<p>El 1982 García-Posada publica nuevas precisiones del mismo «testigo de excepción», como lo define este crítico. Ahora es <em>Adam</em> —soneto escrito en Nueva York, diciembre de 1929— el que resulta confirmado como perteneciente a la serie. García-Posada añade:</p>`,

  q(`Rosales se ratifica hoy en lo declarado a Schönberg —por una vez, hemos de contar con los datos de un crítico tan miserable y, sin embargo, con tantos seguidores— de que este <em>Jardín de sonetos</em> (sic) constaba de treinta y cinco poemas, estaba dividido en dos partes y los más antiguos databan de 1924.`),

  `<p>Por la misma conversación que se reseña sabemos también que, tras la muerte de Lorca, Rosales entregó «algunos sonetos, de los que no sacó copia», a la familia de su amigo. ¿Algunos? ¿No los 30 ó 35? Imaginamos una transcripción inexacta o las imprecisiones, quizá, de una mera conversación. Pero en declaraciones de 1978, Esperanza Rosales, hermana del autor de <em>Abril</em>, recordaba que fue su padre quien llevó los papeles del poeta asesinado a don Federico García Rodríguez. Fuera quien fuera el portador de las cuartillas, en ellas irían los sonetos y, en mi opinión, <em>La casa de Bernarda Alba</em>.</p>`,

  `<p>Sólo como conjetura cabe pensar que el título <em>Jardín de los sonetos</em> no era el definitivo o habría sido sustituido por otro nuevo. La especulación no es atendible, ya que carece de cualquier punto de apoyo. Sí importa, en cambio, examinar el testimonio de Rosales sobre el número de sonetos, aunque luego volvamos sobre el tema desde otra perspectiva. De veinte poemas consta el <em>Diván del Tamarit</em>, otro libro póstumo, aunque terminado (y parcialmente impreso antes de la muerte del poeta). Por su parte, <em>Alondra de verdad</em>, libro de sonetos de Gerardo Diego aparecido en 1941, sólo reúne cuarenta y dos. Cito esta obra poética porque es un ejemplo perfecto, salvadas todas las diferencias, de lo que hubiera podido ser el libro de Lorca. <em>Alondra de verdad</em> es una muestra de la labor sonetística de un poeta del 27 en su madurez, con composiciones fechadas todas ellas antes del estallido de la guerra. Diego sintió incluso la necesidad de añadir en apéndice treinta y siete páginas de notas, una especie de «argumento de la obra». De este modo el poeta santanderino se excusaba quizá de la ausencia de aires marciales (traídos brevemente por los pelos a propósito del soneto penúltimo, <em>Teide</em>), desde el momento en que todos los sonetos quedaban explicados y fechados. Poesía, pues, que se quería anterior, con nobleza que obligaba: «Al terminar la década 1920-1930, la temperatura —y no sólo de la poesía, sino de la vida toda— crecía arrolladora y a la vez y antes que otros síntomas del fuego estallando ya en la superficie, se sucedían magníficos libros de poesía con títulos belicosos, celestes, románticos, verdaderas erupciones apasionadas, pero brotes justamente de los mismos poetas sospechados, tildados de estériles, deshumanos, extranjerizados y otros dicterios. (...) todavía pululan ataques similares, ataques que ahora se suelen decorar de una interferencia seudopolítica...» Libros que parecen aludidos, antes y después de 1930: <em>Espadas como labios</em>, <em>Cántico</em>, <em>Sobre los ángeles</em>, <em>La destrucción o el amor</em>, <em>Donde habite el olvido</em>, tal vez <em>El rayo que no cesa</em>. Al margen de tan justa y digna reacción, el soneto más antiguo de <em>Alondra de verdad</em> está escrito en 1926, la mayor parte se concentra en los años 32 y 35, y el libro se cierra con tres escritos en julio de 1936. Para que la sorpresa comparativa sea mayor, la sección tercera de <em>Alondra de verdad</em> está compuesta por once sonetos escritos al hilo de un viaje, en febrero y marzo de 1935, de vuelta el poeta de Filipinas. Además, algunos de estos poemas se tiñen de sentimiento amoroso.</p>`,

  `<p>Estas similitudes atienden sólo al azar de la composición, como es obvio, pero señalan un paralelo teóricamente previsible entre dos poetas coetáneos. Cierto que no hay que exagerar los puntos de semejanza, atendida la inconclusión del conjunto lorquiano. Lo que quiero subrayar es que, a la hora de ordenar o decidir el índice de un libro —y Diego o Lorca actúa como cualquier mortal poeta—, lo habitual es reunir poemas de fechas no necesariamente próximas. Lo que pudo ser arranque unitario y fervoroso de unos días —un puñado de poemas, rarísima vez un libro entero— puede dar lugar a una sección o al núcleo irradiador del libro futuro, acaso con imposición de una forma métrica. Salvo en casos excepcionales que los mismos poetas han cuidado de relatar, las diferencias entre el proyecto o idea de un libro y su terminación son muy marcadas. El conocimiento que tenemos de la cronología de los poemas lorquianos muestra claramente que la composición de sus libros, si perfectamente calculada, obedece casi siempre a decisiones últimas, de modo que la reconstrucción de los procesos seguidos muestra continuos cambios y entrecruzamientos a partir de uno o más proyectos iniciales. Dentro de este contexto se hace cuesta arriba admitir la esgrimible hipótesis de que el <em>Jardín de los sonetos</em> recogía sólo composiciones de última época. Lo propio es que Lorca, de modo semejante a Diego, decidiera completar la serie de sonetos amorosos, escritos o iniciados en 1935, con el añadido de otros de temática y fechas distintas. El recuerdo de Luis Rosales, aparte de coherente respecto a la composición del libro, adquiere absoluta verosimilitud en este mismo terreno.</p>`,

  `<p>El título, pues, de <em>Jardín de los sonetos</em> queda confirmado por Luisa Camacho y Luis Rosales a través de las primeras consultas de Couffon, Schönberg y Gibson. Es el último del que queda noticia y no cabe dudar sobre su validez. Su estirpe clásica —silvas y jardines de la Edad de Oro— nos lleva al gongorino Soto de Rojas, al consiguiente subtítulo de <em>Doña Rosita</em> —«poema granadino..., dividido en varios jardines»— y se ajusta a la titulación explicativa, al modo barroco, de los sonetos que nos son conocidos. Según todos los indicios, el nacimiento del libro estuvo determinado por la escritura de un breve cancionero de sonetos amorosos, que serían los escuchados por Aleixandre. En una estela petrarquista, Lorca poetiza incluso la cronología de su pasión amorosa, para lo que retoma un verso de estribillo —«¡Qué espesura de anémonas levanta!»— en un romance de <em>Así que pasen cinco años</em>:</p>`,

  `<blockquote>Entre lo que me quieres y te quiero,<br>aire de estrellas y temblor de planta,<br>espesura de anémonas levanta<br>con oscuro gemir un año entero.</blockquote>`,

  `<p>El cambio al título de <em>Jardín</em> sugiere que la temática amorosa había dejado de ser, efectivamente, exclusiva. Esta ampliación del proyecto debió producirse ya en Madrid, pues Cernuda (1954) incluye en la serie otro soneto funeral compuesto en 1936: <em>A Mercedes en su vuelo</em>. Fiel a la imagen que había conservado, Cernuda recalca que el soneto fue «añadido a los demás, con los que no formaba parte».</p>`,
].join("\n");

async function main() {
  const issue = await db.magazineIssue.findFirst({ where: { number: 9 }, select: { id: true, publishedAt: true } });
  if (!issue) throw new Error("No existe el nº9");
  const admin = await db.user.findFirst({ where: { role: "ADMIN" }, select: { id: true } });

  const authorSlug = slugifyName(BYLINE);
  const author = await db.author.upsert({
    where: { slug: authorSlug },
    update: { name: BYLINE },
    create: { name: BYLINE, slug: authorSlug },
  });

  const article = await db.article.upsert({
    where: { slug: SLUG },
    update: { content, status: "PUBLISHED", byline: BYLINE, excerpt: EXCERPT, pages: PAGES, title: TITLE, section: "La fábrica de sueños" },
    create: {
      title: TITLE, slug: SLUG, excerpt: EXCERPT, content, byline: BYLINE, status: "PUBLISHED",
      issueId: issue.id, authorId: admin?.id ?? "", pages: PAGES, section: "La fábrica de sueños",
      publishedAt: issue.publishedAt ?? new Date("1986-01-01T00:00:00Z"),
    },
  });

  await db.authorsOnArticles.deleteMany({ where: { articleId: article.id } });
  await db.authorsOnArticles.create({ data: { articleId: article.id, authorId: author.id, order: 0 } });

  console.log(`✓ ${TITLE} — ${BYLINE} (págs. ${PAGES})`);
  await db.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
